### ISSUE TITLE
request: custom render support

### ISSUE THREAD

**Issue by chobie** [ikwattro/KwattroMarkdownBundle#1]
currently,  KwattroMarkdownBundle can't specify a custom render class.
it would be useful if it can specify.

**Comment by ikwattro** [comment]
Yes, indeed. I've just try to do it now but it requires some refactoring so I will better to do it tomorrow.

I close this one as the issue will be treated in PR #2

**Comment by ikwattro** [comment]
@chobie the PR makes the use of a custom render class possible, I have updated the docs for it also.

grtz
