### ISSUE TITLE
Some extensions non functionnals

### ISSUE THREAD

**Issue by Genokilller** [ikwattro/KwattroMarkdownBundle#5]
Hi,

Some extensions like "no_intra_emphasis" or "lax_html_blocks" seems to not work. 

This is not provide from the KwattroBundle, but it's look like to be from the php-sundown extension. Is it uptodate ?

This seems to be an important bug for me, can you take a look on this issue ?

Thanks ;)

**Comment by ikwattro** [comment]
Hi @Genokilller I will contact the author of the sundown extension.

Thanks for the report.

**Comment by ikwattro** [comment]
https://github.com/chobie/php-sundown/issues/14

**Comment by ikwattro** [comment]
Forgot to close it
